source :rubygems

gem "rails", '2.3.5'

# Specify your favourite web server (only one).
#gem 'unicorn', :group => :development
#gem 'mongrel', :group => :development

gem 'ruby_parser'

group :test do
  gem 'test-unit', '2.1.1'
end