require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe IrbController do

  def mock_irb(stubs={})
    @mock_irb ||= mock_model(Irb, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all irb as @irb" do
      Irb.stub(:all) { [mock_irb] }
      get :index
      assigns(:irb).should eq([mock_irb])
    end
  end

  describe "GET show" do
    it "assigns the requested irb as @irb" do
      Irb.stub(:find).with("37") { mock_irb }
      get :show, :id => "37"
      assigns(:irb).should be(mock_irb)
    end
  end

  describe "GET new" do
    it "assigns a new irb as @irb" do
      Irb.stub(:new) { mock_irb }
      get :new
      assigns(:irb).should be(mock_irb)
    end
  end

  describe "GET edit" do
    it "assigns the requested irb as @irb" do
      Irb.stub(:find).with("37") { mock_irb }
      get :edit, :id => "37"
      assigns(:irb).should be(mock_irb)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created irb as @irb" do
        Irb.stub(:new).with({'these' => 'params'}) { mock_irb(:save => true) }
        post :create, :irb => {'these' => 'params'}
        assigns(:irb).should be(mock_irb)
      end

      it "redirects to the created irb" do
        Irb.stub(:new) { mock_irb(:save => true) }
        post :create, :irb => {}
        response.should redirect_to(irb_url(mock_irb))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved irb as @irb" do
        Irb.stub(:new).with({'these' => 'params'}) { mock_irb(:save => false) }
        post :create, :irb => {'these' => 'params'}
        assigns(:irb).should be(mock_irb)
      end

      it "re-renders the 'new' template" do
        Irb.stub(:new) { mock_irb(:save => false) }
        post :create, :irb => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested irb" do
        Irb.stub(:find).with("37") { mock_irb }
        mock_irb.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :irb => {'these' => 'params'}
      end

      it "assigns the requested irb as @irb" do
        Irb.stub(:find) { mock_irb(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:irb).should be(mock_irb)
      end

      it "redirects to the irb" do
        Irb.stub(:find) { mock_irb(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(irb_url(mock_irb))
      end
    end

    describe "with invalid params" do
      it "assigns the irb as @irb" do
        Irb.stub(:find) { mock_irb(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:irb).should be(mock_irb)
      end

      it "re-renders the 'edit' template" do
        Irb.stub(:find) { mock_irb(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested irb" do
      Irb.stub(:find).with("37") { mock_irb }
      mock_irb.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the irb list" do
      Irb.stub(:find) { mock_irb }
      delete :destroy, :id => "1"
      response.should redirect_to(irb_url)
    end
  end

end
